/* Generated by Opal 0.8.0.rc2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $module = Opal.module;

  Opal.add_stubs(['$push', '$require']);
  (function($base) {
    var self = $module($base, 'Spawn');

    var def = self.$$proto, $scope = self.$$scope, TMP_1;

    self.native_type = Spawn;

    Opal.defs(self, '$system', TMP_1 = function(o) {
      var self = this, $iter = TMP_1.$$p, b = $iter || nil;
      if (self.native_type == null) self.native_type = nil;

      o = $slice.call(arguments, 0);
      TMP_1.$$p = null;
      if (b !== false && b !== nil) {
        o.$push(b)};
      return self.native_type['system'].apply(self.native_type, o);
    });
  })(self);
  return $scope.get('VRbJS').$require("spawn/spawn");
})(Opal);
