/* Generated by Opal 0.8.0.rc2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$extend']);
  return (function(self) {
    var $scope = self.$$scope, def = self.$$proto;

    return self.$extend($scope.get('Spawn'))
  })(self.$singleton_class())
})(Opal);
